namespace Koturn.VRChat.Log.Events
{
    /// <summary>
    /// Represents the method that will handle an event when the event provides data.
    /// </summary>
    /// <typeparam name="TEventArgs">The type of the event data generated by the event.</typeparam>
    /// <param name="sender">The source of the event.</param>
    /// <param name="e">An object that contains the event data.</param>
    /// <remarks>
    /// Unlike <see cref="System.EventHandler{TEventArgs}"/>, <paramref name="sender"/> is notnull.
    /// </remarks>
    public delegate void VRCLogEventHandler<TEventArgs>(object sender, TEventArgs e);
}
